OTUS-877  componente de adição de atividade à nova tela de atividades…
ccem-dev/otus pull request #295
Opened 2021-02-08 21:06 UTC by adonisgarcia

… (por onda)

2021-02-18 22:22 UTC, FlaviaAP requested changes

2021-02-18 22:22 UTC, FlaviaAP commented on source/app/ux-component/activity-adder/activity-adder-component.js
> +        // .then(() => ApplicationStateService.activateActivityAdder())
Este trecho foi comentado temporariamente ou deve ser retirado?

2021-02-19 12:20 UTC, adonisgarcia commented on source/app/ux-component/activity-adder/activity-adder-component.js
> +        // .then(() => ApplicationStateService.activateActivityAdder())
Removido.

2021-02-19 13:17 UTC, FlaviaAP approved these changes

2021-02-19 20:00 UTC, merged